# Generated by Django 4.2.1 on 2023-06-27 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuance',
            name='date_issued',
            field=models.DateTimeField(default='2023-06-27 12:55:58'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity_app.productname'),
        ),
    ]
