# Generated by Django 4.2.1 on 2023-06-28 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commodity_app', '0002_alter_issuance_date_issued_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuance',
            name='date_issued',
            field=models.DateTimeField(default='2023-06-28 11:31:59'),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='serial_no',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
